# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Bénédicte Colnet
email: benedicte.colnet@inria.fr
description: > # this means to ignore newlines until "url:"
  Bénédicte's Colnet Homepage
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme (thanks to them!).
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

url:  # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: BenedicteColnet # put your github username
twitter_username: BenedicteColnet # put your twitter username
scholar_authorid: vEg6pnkAAAAJ&hl=fr # put your google scholar author id
linkedin_username: bénédicte-colnet-a0b628170
contact_note: >
  The best way to reach me remains to contact me by email.

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: "Miscellaneous"
blog_description: Short presentations of side projects.

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  true
enable_anchorjs:    true
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  #projects:
  #  output: true
  #  permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes
include: ['_pages']

# Gems
gems:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Colnet

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
